import { StyleSheet, Platform, StatusBar } from "react-native";

export const getStyles = (theme: any) => {
  const isDark = theme.isDark;
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    scrollContent: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      paddingBottom: 100,
    },
    profileHeader: {
      alignItems: 'center',
      paddingVertical: 32,
      marginBottom: 20,
    },
    avatarContainer: {
      position: 'relative',
      marginBottom: 16,
    },
    avatar: {
      width: 90,
      height: 90,
      borderRadius: 45,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.2)' : 'rgba(58, 167, 122, 0.12)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    editAvatarButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: theme.primary || '#3AA77A',
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    userName: {
      fontSize: 22,
      fontWeight: '800',
      color: theme.text || '#2C2B30',
      marginBottom: 4,
      letterSpacing: 0.5,
    },
    userEmail: {
      fontSize: 15,
      color: theme.subtext || '#616A78',
      fontWeight: '500',
    },
    section: {
      marginBottom: 20,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.1)' : '#FFFFFF',
      borderRadius: 24,
      padding: 24,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.2)' : '#E6F7F0',
      shadowColor: '#2C2B30',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDark ? 0 : 0.04,
      shadowRadius: 8,
      elevation: isDark ? 0 : 1,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.subtext || '#616A78',
      marginBottom: 20,
      letterSpacing: 0.3,
    },
    infoItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    infoLabel: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    iconBg: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.15)' : 'rgba(0, 71, 255, 0.12)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    infoTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.text || '#2C2B30',
    },
    infoValue: {
      fontSize: 14,
      color: theme.text || '#2C2B30',
      fontWeight: '700',
    },
    divider: {
      height: 1,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.2)' : '#ECEEF2',
      marginVertical: 14,
    },
    editButton: {
      marginTop: 16,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: isDark ? 'rgba(255, 255, 255, 0.2)' : '#ECEEF2',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    editButtonText: {
      color: theme.primary || '#3AA77A',
      fontSize: 15,
      fontWeight: '700',
      marginLeft: 8,
    },
    notificationItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    notificationLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    notificationTitle: {
      fontSize: 15,
      color: theme.text || '#2C2B30',
      fontWeight: '600',
    },
    menuItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 6,
    },
    menuLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    menuTitle: {
      fontSize: 15,
      color: theme.text || '#2C2B30',
      fontWeight: '600',
    },
    dangerSection: {
      marginTop: 10,
      marginBottom: 20,
      gap: 12,
    },
    dangerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      backgroundColor: isDark ? 'rgba(225, 29, 72, 0.1)' : '#FFF5F5',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(225, 29, 72, 0.4)' : '#FEE2E2',
    },
    dangerButtonText: {
      fontSize: 16,
      fontWeight: '700',
      marginLeft: 10,
      color: theme.ternary || '#D74247',
    },
    deleteButton: {
      paddingVertical: 16,
      alignItems: 'center',
    },
    deleteButtonText: {
      fontSize: 14,
      color: theme.subtext || '#858D99',
      fontWeight: '600',
    },
    versionText: {
      textAlign: 'center',
      color: theme.subtext || '#858D99',
      fontSize: 13,
      fontWeight: '600',
      marginBottom: 20,
    },
  });
};
