import { StyleSheet, Platform, StatusBar } from "react-native";
import { AppTheme } from "@/src/shared/constants/theme";

export const getStyles = (theme: AppTheme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    scrollContent: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      paddingBottom: 100,
    },
    profileHeader: {
      alignItems: 'center',
      paddingVertical: 32,
      marginBottom: 20,
    },
    avatarContainer: {
      position: 'relative',
      marginBottom: 16,
    },
    avatar: {
      width: 90,
      height: 90,
      borderRadius: 45,
      backgroundColor: theme.avatarBg,
      justifyContent: 'center',
      alignItems: 'center',
    },
    editAvatarButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: theme.buttonPrimary,
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: theme.white,
    },
    userName: {
      fontSize: 22,
      fontWeight: '800',
      color: theme.text,
      marginBottom: 4,
      letterSpacing: 0.5,
    },
    userEmail: {
      fontSize: 15,
      color: theme.subtext,
      fontWeight: '500',
    },
    section: {
      marginBottom: 20,
      backgroundColor: theme.cardBg,
      borderRadius: 24,
      padding: 24,
      borderWidth: 1,
      borderColor: theme.cardBorder,
      shadowColor: theme.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
      elevation: 1,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: theme.subtext,
      marginBottom: 20,
      letterSpacing: 0.3,
    },
    infoItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    infoLabel: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    iconBg: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.badgeBg,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    infoTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.text,
    },
    infoValue: {
      fontSize: 14,
      color: theme.text,
      fontWeight: '700',
    },
    divider: {
      height: 1,
      backgroundColor: theme.divider,
      marginVertical: 14,
    },
    editButton: {
      marginTop: 16,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: theme.divider,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    editButtonText: {
      color: theme.linkText,
      fontSize: 15,
      fontWeight: '700',
      marginLeft: 8,
    },
    notificationItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    notificationLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    notificationTitle: {
      fontSize: 15,
      color: theme.text,
      fontWeight: '600',
    },
    menuItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 6,
    },
    menuLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    menuTitle: {
      fontSize: 15,
      color: theme.text,
      fontWeight: '600',
    },
    dangerSection: {
      marginTop: 10,
      marginBottom: 20,
      gap: 12,
    },
    dangerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      backgroundColor: theme.dangerBg,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.dangerBorder,
    },
    dangerButtonText: {
      fontSize: 16,
      fontWeight: '700',
      marginLeft: 10,
      color: theme.ternary,
    },
    deleteButton: {
      paddingVertical: 16,
      alignItems: 'center',
    },
    deleteButtonText: {
      fontSize: 14,
      color: theme.placeholderText,
      fontWeight: '600',
    },
    versionText: {
      textAlign: 'center',
      color: theme.placeholderText,
      fontSize: 13,
      fontWeight: '600',
      marginBottom: 20,
    },
    acceptedContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 16,
      backgroundColor: theme.successBg,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.successBorder,
      gap: 8,
    },
    acceptedText: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.primary,
    },
  });
};

export default getStyles;
