import { StyleSheet, Platform } from 'react-native';
import { colors } from '@/src/constants/theme';

export const getStyles = (theme: any) => StyleSheet.create({
  sucessheaderContainerToast: {
    flexDirection: 'row',
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.neonVerde,
    paddingVertical: 16,
    paddingHorizontal: 20,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 12,
    marginTop: Platform.OS === 'ios' ? 50 : 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  sucessheaderIndicatorToast: {
    width: 6,
    backgroundColor: theme.neonVerde,
    marginRight: 16,
    borderRadius: 3,
  },
  sucessheaderContentToast: {
    flex: 1,
    justifyContent: 'center',
  },
  sucesstitleRowToast: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  sucessheaderTitleToast: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.neonVerde,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  sucessheaderSubtitleToast: {
    fontSize: 14,
    color: theme.white || colors.white || '#666',
  },

  headerContainerToast: {
    flexDirection: 'row',
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: '#ef4444', // Vermelho para erro
    paddingVertical: 16,
    paddingHorizontal: 20,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 12,
    marginTop: Platform.OS === 'ios' ? 50 : 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  headerIndicatorToast: {
    width: 6,
    backgroundColor: '#ef4444',
    marginRight: 16,
    borderRadius: 3,
  },
  headerContentToast: {
    flex: 1,
    justifyContent: 'center',
  },
  titleRowToast: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  headerTitleToast: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ef4444',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerSubtitleToast: {
    fontSize: 14,
    color: colors.text,
  },

  toastContainer: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: Platform.OS === 'ios' ? 50 : 30,
  },

  edicaoToast: {
    flexDirection: 'row',
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.neon,
    paddingVertical: 16,
    paddingHorizontal: 20,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 12,
    marginTop: Platform.OS === 'ios' ? 50 : 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  edicaoIndicatorToast: {
    width: 6,
    backgroundColor: theme.neon,
    marginRight: 16,
    borderRadius: 3,
  },
  edicaoContentToast: {
    flex: 1,
    justifyContent: 'center',
  },
  edicaotitleRowToast: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  edicaoTitleToast: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.neon,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  edicaoSubtitleToast: {
    fontSize: 14,
    color: theme.text || '#666',
  },

  errorToastLogin: {
    backgroundColor: theme.background,
    borderRadius: 12,
    width: '90%',
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1.5,
    borderColor:  '#fca5a5',
  },
  errorTextLogin: {
    fontSize: 18,
    color: '#dc2626',
    fontWeight: 'bold',
    marginLeft: 12,
  },
  errorSubTextLogin: {
    fontSize: 14,
    color: '#dc2626',
    marginLeft: 12,
    marginTop: 2,
    flexShrink: 1,
  },

  EnvioToastSenha: {
    backgroundColor: theme.background,
    borderRadius: 12,
    width: '90%',
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1.5,
    borderColor: theme.neonVerde,
  },
  EnvioTextSenha: {
    fontSize: 18,
    color: theme.neonVerde,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  EnvioSubTextSenha: {
    fontSize: 14,
    color: theme.text || '#333',
    marginLeft: 12,
    marginTop: 2,
    flexShrink: 1,
  },

  DocToast: {
    backgroundColor: theme.background,
    borderRadius: 12,
    width: '90%',
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1.5,
    borderColor: theme.primary,
  },
  DocText: {
    fontSize: 18,
    color: theme.primary,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  DocSubText: {
    fontSize: 14,
    color: theme.primary,
    marginLeft: 12,
    marginTop: 2,
    flexShrink: 1,
  },
});
