import { StyleSheet, Platform } from 'react-native';

export const getStyles = (theme: any) => {
  const isDark = theme?.isDark;
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme?.background || 'transparent',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'ios' ? 60 : 40,
      paddingBottom: 20,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.1)' : '#F4F5F7',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.2)' : '#E2E8F0',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: theme?.text || '#2C2B30',
      letterSpacing: 0.5,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 100,
    },
    avatarContainer: {
      alignItems: 'center',
      marginTop: 20,
      marginBottom: 40,
      position: 'relative',
      alignSelf: 'center',
    },
    avatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.2)' : '#F4F5F7',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.5)' : '#E2E8F0',
    },
    editAvatarButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: theme?.primary || '#0047FF',
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    formContainer: {
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.05)' : '#FFFFFF',
      borderRadius: 24,
      padding: 24,
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.1)' : '#E2E8F0',
      shadowColor: '#2C2B30',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0 : 0.05,
      shadowRadius: 8,
      elevation: isDark ? 0 : 2,
    },
    saveButton: {
      backgroundColor: theme?.primary || '#0047FF',
      borderRadius: 16,
      height: 56,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
      shadowColor: '#2C2B30',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 5,
      elevation: 5,
    },
    saveButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    locationButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.15)' : '#F4F5F7',
      borderWidth: isDark ? 0 : 1,
      borderColor: isDark ? 'transparent' : '#E2E8F0',
      borderRadius: 12,
      paddingVertical: 14,
      marginTop: 8,
      marginBottom: 16,
    },
    locationButtonText: {
      color: theme?.text || '#2C2B30',
      fontSize: 14,
      fontWeight: '600',
    },
    sliderContainer: {
      marginTop: 8,
      marginBottom: 16,
    },
    sliderLabel: {
      color: theme?.text || '#2C2B30',
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 4,
    },
    sliderRange: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    sliderRangeText: {
      color: theme?.subtext || '#616A78',
      fontSize: 12,
    },
  });
};
